### ISSUE TITLE
Week 05/02/2024

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#138]
Admin:
- [x] Make sure budget is acceptable for CSHL
- [x] Send SICSA form
- [x] Fill and send Risk Asst forms
- [ ] Book confs and accomodations
- [ ] Write Abstract for Cold Harbor if FRF accepted
- [ ] apply to: https://genetics.org.uk/grants/junior-scientist-conference-grants/

Learning:
- [x] TMLE lecture / Semi parametrics / Causal Inference reading
- [ ] Read one paper from Ideas: https://github.com/TARGENE/targene-pipeline/issues/97

TarGene:
- [x] Update pipeline's documentation
- [x] Release targene 0.9
- [ ] Workout serialization format for fast post loading of results

VDR Study:
- [x] Check Permutation Tests
- [ ] [Neg control inflation](https://github.com/TARGENE/targene-pipeline/issues/139)
- [ ] Rerun with new targene release
- [ ] Run Randomized Test
- [ ] https://github.com/TARGENE/targene-pipeline/issues/120

Simulation Study:
- [x] Start working on https://github.com/TARGENE/targene-pipeline/issues/124 ?
- [x] Learn about generative models
