### ISSUE TITLE
Week 19/02/2024

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#144]
Admin:
- [x] Book flights and accomodations Copenhagen

Learning:
- [ ] TMLE lecture / Semi parametrics / Causal Inference reading
- [ ] Read one paper from Ideas: https://github.com/TARGENE/targene-pipeline/issues/97

TarGene:
- [ ] Workout serialization format for fast post loading of results

VDR Study:
- [ ] [Discovery Analysis](https://github.com/TARGENE/targene-pipeline/issues/148)
- [x] [Neg control inflation](https://github.com/TARGENE/targene-pipeline/issues/139)
- [x] Issue with rs150415348 has only one allele, how did it make it through? Maybe not filtered but no estimand.
- [ ] Rerun with new targene release
- [ ] Run Randomized Test
- [x] https://github.com/TARGENE/targene-pipeline/issues/120

Simulation Study:
- [ ] Start to write estimator comparison script https://github.com/TARGENE/targene-pipeline/issues/126
