### ISSUE TITLE
Week 11/03/2024

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#151]
Learning:
- [x] TMLE lecture / Semi parametrics / Causal Inference reading
- [x] Read one paper from Ideas: https://github.com/TARGENE/targene-pipeline/issues/97
- [x] Heidelberg Cnnference

VDR Study:
- [ ] [Trial run Perm Test again](https://github.com/TARGENE/targene-pipeline/issues/153)
- [ ] Rerun with new targene release
- [ ] Run Randomized Test

Simulation Study:
- [x] Start to write estimator comparison script https://github.com/TARGENE/targene-pipeline/issues/126
- [ ] [Density Estimation Simulation](https://github.com/TARGENE/targene-pipeline/issues/154)
- [ ] [Analysis](https://github.com/TARGENE/targene-pipeline/issues/155)
- [ ] Write Configuration File for permutation null sampler
- [ ] Write Configuration File for Density estimation model comparison
- [ ] Write COnfiguration File for Density Estimation Sampler estimation
