### ISSUE TITLE
Week 18/03/2024

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#157]
Learning:
- [x] TMLE lecture / Semi parametrics / Causal Inference reading
- [x] Meta Analysis course
- [ ] Read one paper from Ideas: https://github.com/TARGENE/targene-pipeline/issues/97

MC1R Study:

- [x] Run red hair
- [x] Run non red hair
- [x] compact results
- [x] Send results

VDR Study:
- [x] [Trial run Perm Test again](https://github.com/TARGENE/targene-pipeline/issues/153)
- [ ] Rerun with new targene release

Simulation Study:
- [x] Fix TMPDIR issue (probably just write to local dior instead)
- [ ] [Density Estimation Simulation](https://github.com/TARGENE/targene-pipeline/issues/154)
- [ ] [Analysis](https://github.com/TARGENE/targene-pipeline/issues/155)
- [ ] Write Configuration File for permutation null sampler
- [ ] Write Configuration File for Density estimation model comparison
- [ ] Write COnfiguration File for Density Estimation Sampler estimation
