### ISSUE TITLE
Todo before publication

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#75]
Todo list:

- [x] Migrate the project to: https://github.com/edbiomedai/targene-paper
- [ ] Update README.md
- [x] Check the sieve variance once it is rerun

FTO:

- [x] Rerun FTO with weighted fluctuation
- [x] Rerun FTO analyses to check if anything changed
- [ ] Run FTO negative controls permutation tests
- [ ] Update README.md

Hair color:

- [x] Rerun hair/skin colour with weighted fluctuation
- [x] Add hair color to the run since this is the original reproducibility attempt
- [x] Rerun skin colour analyses to check if anything changed
- [x] Investigate failed TMLEs (missing results and a failed Process)
- [ ] Potentially run negative controls permutation tests
- [ ] Update README.md

VDR:

- [x] Rerun VDR with weighted fluctuation
- [x] Rerun VDR analyses to check if anything changed
- [ ] Potentially run negative controls permutation tests
- [ ] Update README.md

Environmental Interaction:

- [x] Ask Josh for the setup
- [x] Run
- [ ] Update README.md

**Comment by olivierlabayle** [comment]
- [ ] Update non-linearity plot.
- [ ] Compute the number of time we cover the gene ATLAS (continuous) or Neale v2.
